liip_imagine:
    data_loader: bigfoot_media
    filter_sets:
        media_thumbnail:
            quality: 90
            filters:
                thumbnail:  { size: [100, 100], mode: outbound }
        media_single:
            quality: 90
            filters:
                thumbnail:  { size: [300, 200], mode: outbound }
        media_gallery:
            quality: 90
            filters:
                thumbnail:  { size: [500, 250], mode: outbound }
